// ============================================================================
// 6-Layer Intelligence Report — Barrel Exports
// OLD exports preserved in index.old.ts
// ============================================================================

export { default as ReportView } from './ReportView';
export type {
  ReportData,
  LayerId,
  RiskLevel,
  Sentiment,
  VerdictType,
  Verdict,
  LayerOverview,
  L1OfficialNarrative,
  L1PageSurface,
  L1CoreWebProperties,
  L1SocialBrandAccount,
  L1MediaChannels,
  L1HiringSurface,
  L1ProductSurfaces,
  L1InvestorSurfaces,
  L1LegalSurfaces,
  L1RegionalVariant,
  L1EdgeCase,
  L2ProfessionalBehavior,
  L2Signal,
  L2DevSignal,
  L2SpeakerClass,
  L2Tone,
  L2Category,
  L3EmployeeLeakage,
  L3Review,
  L4CommunityReality,
  L4Discussion,
  L5ClientFallout,
  L5Complaint,
  L6ExternalConsequences,
  L6Event,
  NarrativeMismatch,
  CrossLayerInsight,
  PatternTimeline,
  TimelineTheme,
  TimelineEvent,
  RiskRewardItem,
  First90Days,
  Checklist,
  ChecklistItem,
  RedFlag,
  QuestionCategory,
  YouTubeEvidence,
  YouTubeVideo,
  InterviewIntelligence,
  InterviewStage,
  EvidenceSection,
  EvidenceSource,
  CandidateInfo,
} from './types';
